### PR TITLE
Allow task-metadata to be cleaned up from plugins

### PR DESCRIPTION
**Pull request by lbradstreet**

### CODE REVIEW

**Comment by lbradstreet** [comment]
Needs a quick QC from @MichaelDrogalis if he has a moment. I'll put this one in 0.7.3.

**Comment by MichaelDrogalis** [comment]
This should also be dissoc'ed during GC

**Comment by lbradstreet** [comment]
Damn. I knew I forgot something.

**Comment by lbradstreet** [comment]
I think this is enough. A quick re-qc after build pass would be good though.

**Comment by MichaelDrogalis** [comment]
Good to go! Thanks:)

**Pull request merged**
