### PR TITLE
First-cut of User Guide updates

### PR DESCRIPTION
**Pull request by vijaykiran**
- Markdown files are now asciidoc files (using pandoc, and manual hand-holding)
- Links are fixed (internal and external)
- Order of the user guide is now updated.

### CODE REVIEW

**Comment by vijaykiran** [comment]
You can check the full doc here: https://htmlpreview.github.io/?https://github.com/vijaykiran/onyx/blob/adoc-userguide/doc/user-guide/full.html

**Comment by dignati** [comment]
The event subscription example looks a bit broken. Compare https://htmlpreview.github.io/?https://github.com/vijaykiran/onyx/blob/adoc-userguide/doc/user-guide/full.html#event-subscription and http://www.onyxplatform.org/docs/user-guide/latest/subscription.html

**Comment by vijaykiran** [comment]
@dignati thanks! - fixing it.

**Comment by MichaelDrogalis** [comment]
@vijaykiran Cool, thanks. Just let me know when this is ready for review and I'll get the process going!

**Comment by vijaykiran** [comment]
*ping* @MichaelDrogalis ^

**Comment by MichaelDrogalis** [comment]
@vijaykiran Received. Will look at getting this in within the next few days. Thank you!

**Comment by MichaelDrogalis** [comment]
Hasn't dropped off my radar. Will get this merged in next week -- traveling at the moment.

**Comment by MichaelDrogalis** [comment]
Fantastic work @vijaykiran. Getting this out today. :)

**Pull request merged**
