### PR TITLE
Use the peer id of the joiner to generate the aeron id.

### PR DESCRIPTION
**Pull request by dignati**

### CODE REVIEW

**Comment by dignati** [comment]
Maybe use the hash as an index in the vec of available short-ids instead? The worst case complexity is pretty bad with this change.

**Comment by lbradstreet** [comment]
You're right, that's the big flaw in this approach. Yes, maybe it's better to filter the allocated ids out, then hash mod, and pull out the element with that index.

**Comment by dignati** [comment]
Much better code as well.

**Comment by MichaelDrogalis** [comment]
:+1:

**Comment by lbradstreet** [comment]
Perfect - thanks for knocking this one off!

**Pull request merged**
