### PR TITLE
Lifecycle exceptions

### PR DESCRIPTION
**Pull request by MichaelDrogalis**
Implements the feature for #315.

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
@lbradstreet Needs more tests, will add tomorrow. Opened PR for initial review.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Added gen tests. :+1: Ready to go.

**Comment by MichaelDrogalis** [comment]
Looks like this is causing problems for the windowing crash test. Looking into it.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Gonna merge this one, I have a refactoring that's blocked by this that I don't want to get stale.

**Comment by lbradstreet** [comment]
Yup, looked good to me anyway. Sorry for the delay.

**Comment by MichaelDrogalis** [comment]
No worries!

**Pull request merged**
