### PR TITLE
Add generative tests for flow condition validation

### PR DESCRIPTION
**Pull request by mushketyk**
Added generative tests for the following conditions:

>> If a flow condition specifies **:all** as its **:flow/to**, it must come before any other flow conditions. If a flow condition specifies **:none** as its **:flow/to**, it must come directly behind an :all condition, or first if there is no **:all** condition.

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
I'll check this out when I'm back from vacation on Monday. Thanks!!

**Comment by MichaelDrogalis** [comment]
I think we can change this test a little bit to make it perform many more assertions in a shorter amount of time.

As far as generating test data, on branch `develop`, I recently made a series of [generators for flow conditions](https://github.com/onyx-platform/onyx/blob/develop/test/onyx/flow_conditions/flow_conditions_gen_test.clj#L12-L76). We can factor these into their own file and reuse them for your tests if it helps you.

In terms of performing the assertions, the test as is generates a series of conditions and runs a loop-within-a-loop to scan for correct order - which will yield `n^2` performance. I have a trick that we can use to speed it up.

Instead of generating a random series of flow conditions, it is safe to generate a series for only one task - removing the need to check if the transition matches. Further, we can generate flow condition vectors in the series of `[<matches all>, <matches none>]`. If we let test.check generate two vectors, one with `:flow/to` set to `:all`, and the other set to `:none`, you can concat them together and know exactly which position in the final vector that your flow condition to search for is indexed at, giving you constant time look up.

I wouldn't follow *exactly* the instructions above (haven't had my coffee yet!), but does the idea make sense?

Thanks for generously spending your time on this. :)

**Comment by mushketyk** [comment]
Just to make sure that we understand each other. You suggest, for each test, to generate flow conditions that violate a specific rule and check if all generated flow conditions fail flow conditions validation?

It does make sense, and definitely should work much faster.

**Comment by MichaelDrogalis** [comment]
Exactly :)

**Comment by mushketyk** [comment]
Cool :) I'll work on it in few days.

**Comment by mushketyk** [comment]
Closing to change target branch to "develop".

**Pull request closed without merging**
