### PR TITLE
Replace hand-rolled scheduler with BtrPlace

### PR DESCRIPTION
**Pull request by MichaelDrogalis**
Say goodbye to that nasty code, and hello to BtrPlace. Equivalent functionality.

### CODE REVIEW

**Comment by lbradstreet** [comment]
How about setting the random seed to use a hash of the onyx/id? That would at least randomise while staying fixed for that cluster.

**Comment by lbradstreet** [comment]
This is really fantastic. I'm so glad we found BtrPlace - the sky's the limit from here!

**Comment by MichaelDrogalis** [comment]
I see a few problems with not using a globally predetermined seed:

- If we use `:onyx/id`, any bug reports that involve replaying the log will give us the wrong results if we receive the wrong ID from the reporter.
- If we use `:created-at` for the first log entry, we need to add code in the log reader path to handle the first entry separately. This becomes more obscure after the log is GC'ed, as the first log entry present is not the first log entry in history.
- Probably most importantly in my mind, deploying the same job with the exact same replica to a cluster with a different `:onyx/id` or `:created-at` will produce two different performance profiles. It's ideal to make the physical topology as predictable as possible. I'd be very surprised as a user to learn that an identifier could be the sole source of processes being deployed on different machines in an otherwise fully deterministic process.

**Comment by lbradstreet** [comment]
You're right. Testability and ease of reproducibility are big losses. My main concern was that particularly bad behaviours for certain cases would always result in the same bad behaviour for all users. But this should probably just get fixed and it'd be harder to track them down without being able to track the seed, though I think this could be improved simply by dumping the seed with the log. 

It's hard for us to reproduce conditions without a full log dump anyway.

On balance I think fixing the seed is the right approach for now.

**Comment by lbradstreet** [comment]
I increased the TEST_CHECK_FACTOR and ran a bunch of tests locally. This is a failure that I hit:

```
lein test onyx.scheduler.percentage-grouping-generative-test                                                                                                                                                                                                          [776/1231]

Tests failed, smallest case: [{log [[{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p2}, :message-id 0} {:instant-join :p2}] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p5}, :message-id 1} {:observer :p2, :subject :p5}] [{:f
n :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p9}, :message-id 2} nil] [{:fn :notify-join-cluster, :args {:observer :p5, :subject :p2}, :message-id 3} {:observer :p5, :subject :p2, :accepted-observer :p2, :accepted-joiner :p5}] [{:fn :prepare-join-clus
ter, :args {:peer-site {:address 1}, :joiner :p6}, :message-id 4} nil] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p1}, :message-id 5} nil] [{:fn :accept-join-cluster, :args {:observer :p5, :subject :p2, :accepted-observer :p2, :accepted-joiner :
p5}, :message-id 6} {:observer :p2, :subject :p5}] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p4}, :message-id 7} {:observer :p5, :subject :p4}] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p7}, :message-id 8} nil] [{:fn
 :notify-join-cluster, :args {:observer :p4, :subject :p2}, :message-id 9} {:observer :p4, :subject :p2, :accepted-observer :p5, :accepted-joiner :p4}] [{:fn :accept-join-cluster, :args {:observer :p4, :subject :p2, :accepted-observer :p5, :accepted-joiner :p4}, :message-
id 10} {:observer :p5, :subject :p4}] [{:fn :abort-join-cluster, :args {:id :p6}, :message-id 11} nil] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p10}, :message-id 12} {:observer :p2, :subject :p10}] [{:fn :abort-join-cluster, :args {:id :p9}, :
message-id 13} nil] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p8}, :message-id 14} {:observer :p5, :subject :p8}] [{:fn :abort-join-cluster, :args {:id :p7}, :message-id 15} nil] [{:fn :notify-join-cluster, :args {:observer :p8, :subject :p4},
:message-id 16} {:observer :p8, :subject :p4, :accepted-observer :p5, :accepted-joiner :p8}] [{:fn :accept-join-cluster, :args {:observer :p8, :subject :p4, :accepted-observer :p5, :accepted-joiner :p8}, :message-id 17} {:observer :p5, :subject :p8}] [{:fn :prepare-join-c
luster, :args {:joiner :p9, :peer-site {:address 1}}, :message-id 18} {:observer :p5, :subject :p9}] [{:fn :prepare-join-cluster, :args {:joiner :p6, :peer-site {:address 1}}, :message-id 19} {:observer :p8, :subject :p6}] [{:fn :notify-join-cluster, :args {:observer :p10
, :subject :p5}, :message-id 20} {:observer :p10, :subject :p5, :accepted-observer :p2, :accepted-joiner :p10}] [{:fn :abort-join-cluster, :args {:id :p1}, :message-id 21} nil] [{:fn :notify-join-cluster, :args {:observer :p6, :subject :p4}, :message-id 22} {:observer :p6
, :subject :p4, :accepted-observer :p8, :accepted-joiner :p6}] [{:fn :prepare-join-cluster, :args {:joiner :p1, :peer-site {:address 1}}, :message-id 23} {:observer :p4, :subject :p1}] [{:fn :accept-join-cluster, :args {:observer :p6, :subject :p4, :accepted-observer :p8,
 :accepted-joiner :p6}, :message-id 24} {:observer :p8, :subject :p6}] [{:fn :prepare-join-cluster, :args {:peer-site {:address 1}, :joiner :p3}, :message-id 25} {:observer :p8, :subject :p3}] [{:fn :notify-join-cluster, :args {:observer :p1, :subject :p2}, :message-id 26
} {:observer :p1, :subject :p2, :accepted-observer :p4, :accepted-joiner :p1}] [{:fn :accept-join-cluster, :args {:observer :p1, :subject :p2, :accepted-observer :p4, :accepted-joiner :p1}, :message-id 27} {:observer :p4, :subject :p1}] [{:fn :accept-join-cluster, :args {
:observer :p10, :subject :p5, :accepted-observer :p2, :accepted-joiner :p10}, :message-id 28} {:observer :p2, :subject :p10}] [{:fn :notify-join-cluster, :args {:observer :p3, :subject :p6}, :message-id 29} {:observer :p3, :subject :p6, :accepted-observer :p8, :accepted-j
oiner :p3}] [{:fn :prepare-join-cluster, :args {:joiner :p7, :peer-site {:address 1}}, :message-id 30} {:observer :p4, :subject :p7}] [{:fn :notify-join-cluster, :args {:observer :p7, :subject :p1}, :message-id 31} {:observer :p7, :subject :p1, :accepted-observer :p4, :ac
cepted-joiner :p7}] [{:fn :accept-join-cluster, :args {:observer :p3, :subject :p6, :accepted-observer :p8, :accepted-joiner :p3}, :message-id 32} {:observer :p8, :subject :p3}] [{:fn :notify-join-cluster, :args {:observer :p9, :subject :p8}, :message-id 33} {:observer :p
9, :subject :p8, :accepted-observer :p5, :accepted-joiner :p9}] [{:fn :accept-join-cluster, :args {:observer :p9, :subject :p8, :accepted-observer :p5, :accepted-joiner :p9}, :message-id 34} {:observer :p5, :subject :p9}] [{:fn :accept-join-cluster, :args {:observer :p7,
:subject :p1, :accepted-observer :p4, :accepted-joiner :p7}, :message-id 35} {:observer :p4, :subject :p7}] [{:fn :submit-job, :args {:exempt-tasks (), :saturation Infinity, :task-percentages {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" 20, #uuid "2e90aaf0-fb54-4d3b-b2e3
-5e638c49212a" 30, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" 50}, :acker-exclude-outputs false, :min-required-peers {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" 1, #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" 4, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" 1}, :task-s
cheduler :onyx.task-scheduler/percentage, :tasks (#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974"), :inputs (#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece"), :flux-policies {#uuid "2e90aa
f0-fb54-4d3b-b2e3-5e638c49212a" :kill}, :id #uuid "f55c14f0-a847-42eb-81bb-0c0390a88608", :outputs (#uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974"), :acker-percentage 1, :acker-exclude-inputs false, :task-saturation {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" Infinity, #u
uid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" 4, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" Infinity}}, :message-id 36} {:job #uuid "f55c14f0-a847-42eb-81bb-0c0390a88608"}]], replica {:exempt-tasks {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" []}, :peer-sites {:p2 {:addre
ss 1, :port 1}, :p4 {:address 1, :port 1}, :p3 {:address 1, :port 1}, :p5 {:address 1, :port 1}, :p8 {:address 1, :port 1}, :p9 {:address 1, :port 1}, :p1 {:address 1, :port 1}, :p7 {:address 1, :port 1}, :p10 {:address 1, :port 1}, :p6 {:address 1, :port 1}}, :output-tas
ks {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" [#uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974"]}, :job-scheduler :onyx.job-scheduler/greedy, :saturation {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" Infinity}, :task-percentages {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608
" {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" 20, #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" 30, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" 50}}, :peers [:p2 :p5 :p4 :p8 :p6 :p1 :p10 :p3 :p9 :p7], :acker-exclude-outputs {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608"
false}, :min-required-peers {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" 1, #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" 4, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" 1}}, :task-slot-ids nil, :accepted {}, :jobs [#uuid "f55
c14f0-a847-42eb-81bb-0c0390a88608"], :tasks {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" [#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974"]}, :pairs {:p2 :p10, :p4 :p7, :p3 :p6, :p5 :p9
, :p8 :p3, :p9 :p8, :p1 :p2, :p7 :p1, :p10 :p5, :p6 :p4}, :flux-policies {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" {#uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" :kill}}, :messaging {:onyx.messaging/impl :dummy-messenger}, :allocations {#uuid "f55c14f0-a847-42eb-81bb-0
c0390a88608" {}}, :prepared {}, :input-tasks {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" [#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece"]}, :acker-percentage {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" 1}, :peer-state {:p2 :idle, :p4 :idle, :p3 :idle, :p5 :idle, :p8 :id
le, :p9 :idle, :p1 :idle, :p7 :idle, :p10 :idle, :p6 :idle}, :acker-exclude-inputs {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" false}, :task-schedulers {#uuid "f55c14f0-a847-42eb-81bb-0c0390a88608" :onyx.task-scheduler/percentage}, :task-saturation {#uuid "f55c14f0-a847
-42eb-81bb-0c0390a88608" {#uuid "8bb2e1ca-cc0c-4922-b6a6-e4e6019b0ece" Infinity, #uuid "2e90aaf0-fb54-4d3b-b2e3-5e638c49212a" 4, #uuid "fb19d14b-f5f7-4b7d-8680-386ae3aaf974" Infinity}}}, peer-choices [:p2 :p5 :p9 :p2 :p6 :p1 :p5 :p4 :p7 :p5 :p4 :p6 :p10 :p9 :p8 :p7 :p5 :p
8 :p9 :p6 :p2 :p1 :p8 :p1 :p6 :p3 :p4 :p1 :p10 :p8 :p7 :p4 :p3 :p5 :p9 :p7 :job-1]}]
Seed 1451573440609

lein test :only onyx.scheduler.percentage-grouping-generative-test/min-peers-one-job-upper-bound

FAIL in (min-peers-one-job-upper-bound) (percentage_grouping_generative_test.clj:163)
Checking that exactly 4 peers are assigned to task B, and that the extra 10%
      needed to get 4 peers for B are taken from task C.
expected: 2
  actual: 0
    diff: - 2
          + 0

lein test :only onyx.scheduler.percentage-grouping-generative-test/min-peers-one-job-upper-bound

FAIL in (min-peers-one-job-upper-bound) (percentage_grouping_generative_test.clj:164)
Checking that exactly 4 peers are assigned to task B, and that the extra 10%
      needed to get 4 peers for B are taken from task C.
expected: 4
  actual: 0
    diff: - 4
          + 0

lein test :only onyx.scheduler.percentage-grouping-generative-test/min-peers-one-job-upper-bound

FAIL in (min-peers-one-job-upper-bound) (percentage_grouping_generative_test.clj:165)
Checking that exactly 4 peers are assigned to task B, and that the extra 10%
      needed to get 4 peers for B are taken from task C.
expected: 4
  actual: 0
    diff: - 4
          + 0
```

**Comment by MichaelDrogalis** [comment]
@lbradstreet Thanks. I dug in and found that the root cause of this issue is in the percentage task scheduler. This issue was always present, but was likely being fixed downstream, further away from the root cause.

**Comment by MichaelDrogalis** [comment]
Pushed the fix, tests passing.

**Comment by lbradstreet** [comment]
Fantastic work. The cleanup you did at the same time is great. It makes the code a lot clearer. Merging!

**Pull request merged**
