### PR TITLE
6 keys/functions/etc seems to be 9 now

### PR DESCRIPTION
**Pull request by jackdempsey**
Was a bit confusing, seems just like a typo.

### CODE REVIEW

**Comment by jackdempsey** [comment]
Hmm, I'm realizing only 6 functions actually do return a map, so maybe the fix is to change other wording? Anyway, some clarification here would be good.

**Comment by MichaelDrogalis** [comment]
@jackdempsey I'll reword this and post back on completion. Thanks for the report!

**Comment by MichaelDrogalis** [comment]
@jackdempsey Sorry this took a while to get to. I just went ahead and fixed it in 35049f666f9be57727cee2dd8b8cd0fdb526b888 since the patch needs to go to develop first. Thanks for bringing it up!

**Comment by jackdempsey** [comment]
Awesome @MichaelDrogalis thanks!

**Pull request closed without merging**
