### PR TITLE
Clojure 1.10 fixes

### PR DESCRIPTION
**Pull request by solatis**
With Clojure 1.10 being released, there were two additional `namespace` issues that this PR resolves. This makes Onyx fully compatible with Clojure 1.10.

### CODE REVIEW

**Comment by lbradstreet** [comment]
Thanks! I’ll get a release out soon

**Comment by jsab** [comment]
Any ETA for that release @lbradstreet ?

**Comment by lbradstreet** [comment]
@jsab was this not covered by 0.14.1? 0.14.1 included the fixes from this PR. If not, another PR may be required.

**Comment by jsab** [comment]
@lbradstreet See https://github.com/onyx-platform/onyx/blob/0.14.x/src/onyx/state/serializers/windowing_key_decoder.clj#L3 ([permalink](https://github.com/onyx-platform/onyx/blob/b80c6e3b5ea4167380456d01c964488d1ef9e160/src/onyx/state/serializers/windowing_key_decoder.clj#L3))

Fix is not in `0.14.x`.

However it is in `master`: https://github.com/onyx-platform/onyx/blob/master/src/onyx/state/serializers/windowing_key_decoder.clj#L3 ([permalink](https://github.com/onyx-platform/onyx/blob/fb1142ee5d237464b68622ec7e7b74d9c19f731c/src/onyx/state/serializers/windowing_key_decoder.clj#L3))

> another PR may be required.

A PR from `master` to `0.14.x` ?

**Comment by solatis** [comment]
I can confirm that this patch is not yet released in 0.14.1. I think that release did include a patch from @puredanger , but there were a few additional modifications required for full clojure 1.10 support.

**Comment by lbradstreet** [comment]
Thanks, I may just have to make another release then. I’ll find out what went wrong. 

Cheers

Lucas

**Comment by lbradstreet** [comment]
Ah, ok that makes sense. Thanks!

**Comment by jsab** [comment]
@lbradstreet Sorry to bother you about this but any progress with the release?

**Comment by lbradstreet** [comment]
@jsab sorry about that. I'm unable to spend much time on maintaining onyx these days.

I've cut 0.14.2. Assuming it makes its way through the build system successfully, it should be ready for use soon.

**Comment by lbradstreet** [comment]
Resolved by onyx 0.14.4.

**Comment by jsab** [comment]
Big thanks, I can confirm 0.14.4 is working with clojure 1.10.

**Pull request merged**
