### PR TITLE
Move monitoring config into peer config

### PR DESCRIPTION
**Pull request by dignati**

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
Cheers @dignati. Will review this as soon as I can.

@lbradstreet What do you think about timing for integrating this patch since it's a backwards breaking change? I don't think it's terrible disruptive, but would like to consider when is best.

**Comment by dignati** [comment]
Sure, this can wait. Let me know if you would like to see some changes, I basically just searched for `monitoring-config` and used the `peer-config` or, for `start-env`, `env-config` instead. Maybe I missed something.

**Comment by MichaelDrogalis** [comment]
I think that should pretty much do it, yep.

**Comment by lbradstreet** [comment]
Sorry, I totally missed this. I'll give this a look tomorrow. Thanks @dignati.

**Comment by lbradstreet** [comment]
Happy with this. Thanks!

**Pull request merged**
