### PR TITLE
Fixed invalid link in plugin documentation

### PR DESCRIPTION
**Pull request by KevinGreene**

### CODE REVIEW

**Comment by lbradstreet** [comment]
Ah. Thanks. I actually removed that log command completely now that we now do it in onyx internally. I'll just delete that sentence instead. Cheers!

**Comment by KevinGreene** [comment]
My mistake, didn't fully look at the surrounding documentation. I'm not 100% sure, but I think the paragraph before, and maybe a little more, should be deleted, but I don't know for sure.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Closing, unless you wanted anything else from this patch. Thanks @KevinGreene!

**Comment by lbradstreet** [comment]
Thanks @KevinGreene, cleaned up in 669a226

**Pull request closed without merging**
