### PR TITLE
Reuse previous predicate example (actually taking a predicate parameter)

### PR DESCRIPTION
**Pull request by malesch**

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
Thanks @malesch! Can you switch the branch to `develop`? Happy to merge then.

**Comment by MichaelDrogalis** [comment]
Oh wow, apparently I can switch the branch. Cool. Merging!

**Comment by MichaelDrogalis** [comment]
Er, wait -- nope. I screwed it up. Can you rebase against develop? It's trying to drag old commits in.

**Comment by MichaelDrogalis** [comment]
Thanks :D

**Comment by malesch** [comment]
Thank you! 
You and Lucas are doing a **great** job and hope I find a nice for Onyx here at our place. By the way, I worked through your very helpful _learn-onyx_ and maybe have another PR for some changes (no bugs, only minor, minor suggestions or questions from my side ;-)). Thanks again!!

**Comment by MichaelDrogalis** [comment]
Perfect, thanks!!

**Pull request merged**
