### PR TITLE
Fix bulk function execution with empty segments

### LINKED ISSUE #260: Bulk functions get invoked with empty sequences
If a batch times out and returns zero segments, bulk functions are invoked anyway with the empty seq. If a batch is empty, no call should occur.

### PR DESCRIPTION
**Pull request by tvanhens**
Fixes #260

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
@tvanhens Thanks for the fix! Can we switch `empty` to `(not (seq))` per Clojure's [docs](https://clojuredocs.org/clojure.core/empty_q)? Truthfully I don't know why this is preferable, but I've seen it all over the place.

**Comment by lbradstreet** [comment]
Is that actually the recommendation? I read it as use (seq x) as a form of 'not empty'

**Comment by tvanhens** [comment]
`(when-not (seq segments) ...)` or `(when (not (seq segments)) ... )`
The second version feels a little gross imo.

**Comment by MichaelDrogalis** [comment]
The first one is good to me.

**Comment by MichaelDrogalis** [comment]
Thanks for making that (possibly frivolous) change. :)

**Comment by tvanhens** [comment]
I made it an amend since I'm on a fork and its a small change. Wanted to keep the commit log clean. Hope thats alright.

**Comment by MichaelDrogalis** [comment]
:+1

**Pull request merged**
